INSERT INTO `t_title` VALUES ('1', '销售部部长', '.全面负责营销部的工作，负责营销部所有业务', '1');
INSERT INTO `t_title` VALUES ('2', '销售部科长', '在市场部部长的领导下，负责组织本部销售人员不断开拓市场', '5');
INSERT INTO `t_title` VALUES ('3', '销售部组长', '汇报对象， 直接向运销管理部部长报告， 并直接受其领导', '5');
INSERT INTO `t_title` VALUES ('4', '销售员', '负责产品的市场渠道开拓与销售工作，执行并完成公司产品年度销售计划', '5');
INSERT INTO `t_title` VALUES ('5', '人事部部长', '负责公司人力资源的管理，为公司提供和培养合格的人才', '1');
INSERT INTO `t_title` VALUES ('6', '人事部人事专员', '负责公司负责招聘人才', '1');
INSERT INTO `t_title` VALUES ('7', '人事部薪酬福利专员', '负责福利社保工资', '1');
INSERT INTO `t_title` VALUES ('8', '财务部长', '组织领导本公司的财务管理', '2');
INSERT INTO `t_title` VALUES ('9', '财务部项目经理', '它要负责公司的财务经营状况', '2');
INSERT INTO `t_title` VALUES ('10', '财务主管', '它要负责总账等主要财务工作', '2');
INSERT INTO `t_title` VALUES ('11', '财务部一般会计', '日常记账等', '2');
INSERT INTO `t_title` VALUES ('12', '财务部出纳', '负责现金和银行的日记账', '2');
INSERT INTO `t_title` VALUES ('13', '技术部主管', '组织制定和实施技术方案，产品研究开发方案与产品质量管理制度', '3');
INSERT INTO `t_title` VALUES ('14', '技术部技术支持经理', '为客户及相关人员提供与公司相关的技术支持及技术服务', '3');
INSERT INTO `t_title` VALUES ('15', '技术部研发主管', '主持新产品的研发实现公司的产品开发目标', '3');
INSERT INTO `t_title` VALUES ('16', '技术部产品研发工程师', '组织研制，设计，开发新产品及更新换代产品，提供技术支持', '3');
INSERT INTO `t_title` VALUES ('17', '技术部产品开发人员', '协助产品开发工程师，完成产品研制，开发的日常事务工作', '3');
INSERT INTO `t_title` VALUES ('18', '后勤部科长', '分配工作任务，完成后勤人员的协调工作', '4');
INSERT INTO `t_title` VALUES ('19', '后勤部办事员', '负责保持环境清洁，负责员工食堂，宿舍的日常管理', '4');
INSERT INTO `t_title` VALUES ('20', '测试部经理', '制定测试方案及计划，包括人员安排，测试进度，测试流程', '6');
INSERT INTO `t_title` VALUES ('21', '高级软件测试工程师', '熟练掌握软件测试与开发技术，且对所测试软件对口行业非常了解，能够对可能出现的问题进行分析评估', '6');
INSERT INTO `t_title` VALUES ('22', '中级软件测试工程师', '编写软件测试方案、测试文档，与项目组一起制定软件测试阶段的工作计划，能够在项目运行中合理利用测试工具完成测试任务', '6');
INSERT INTO `t_title` VALUES ('23', '初级软件测试工程师', '其工作通常都是按照软件测试方案和流程对产品进行功能测验，检察产品是否有缺陷', '6');
commit;